version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "--no-cache"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./js:/var/www/html/js